name: Main

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+.rc[0-9]+'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "Keyword Item Distributor"
      FOMOD_MOD_AUTHOR: "powerofthree"
      FOMOD_MOD_NEXUS_ID: "55728"
      FOMOD_SE_MIN_GAME_VERSION: '1.5'
      FOMOD_AE_NAME: 'SSE v1.6+ ("Anniversary Edition")'
      FOMOD_AE_DESCR: 'Select this if you are using Skyrim Anniversary Edition v1.6 or higher.'
      FOMOD_AE_MIN_GAME_VERSION: '1.6'
      PUBLISH_ARCHIVE_TYPE: '7z'
      VCPKG_COMMIT_ID: '43d81795a513e2ca6648354786178714f33c8b6f'
